source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'HWPopController_Example' do
  pod 'HWPopController', :path => '../'
  pod 'Masonry'

target 'HWPopController_Tests' do
    inherit! :search_paths

    
  end
end

target 'swiftExample' do
  platform :ios, '13.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'HWPopController', :path => '../'

end
